[2020-03-20 18:15:25,486.486]: start tool
[2020-03-20 18:15:36,039.039]: could not open port 'COM4': WindowsError(5, '\xbe\xdc\xbe\xf8\xb7\xc3\xce\xca\xa1\xa3')
Traceback (most recent call last):
  File "main.py", line 473, in handle_open_com
  File "host_trace.pyo", line 492, in open
  File "serial\serialwin32.pyo", line 31, in __init__
  File "serial\serialutil.pyo", line 180, in __init__
  File "serial\serialwin32.pyo", line 62, in open
SerialException: could not open port 'COM4': WindowsError(5, '\xbe\xdc\xbe\xf8\xb7\xc3\xce\xca\xa1\xa3')
